version: '3.9'
services:
  postgres:
    container_name: taskmanager
    image: taskmanager:latest
    environment:
      POSTGRES_DB: "taskmanager"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
